use_frameworks!

platform :ios, '9.0'

target 'ZJBaseKit_Example' do
  pod 'ZJBaseKit', :path => '../'

  target 'ZJBaseKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
